package rpc;

/**
 * Created by 周思成 on  2020/5/7 11:53
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logOuter.proto



public final class LogOuter {
    private LogOuter() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface LogEntryOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protobuf.LogEntry)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 term = 1;</code>
         */
        long getTerm();

        /**
         * <code>int64 index = 2;</code>
         */
        long getIndex();

        /**
         * <code>bytes data = 3;</code>
         */
        com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code protobuf.LogEntry}
     */
    public  static final class LogEntry extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protobuf.LogEntry)
            LogEntryOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use LogEntry.newBuilder() to construct.
        private LogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private LogEntry() {
            term_ = 0L;
            index_ = 0L;
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private LogEntry(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            term_ = input.readInt64();
                            break;
                        }
                        case 16: {

                            index_ = input.readInt64();
                            break;
                        }
                        case 26: {

                            data_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return rpc.LogOuter.internal_static_protobuf_LogEntry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return rpc.LogOuter.internal_static_protobuf_LogEntry_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            rpc.LogOuter.LogEntry.class, rpc.LogOuter.LogEntry.Builder.class);
        }

        public static final int TERM_FIELD_NUMBER = 1;
        private long term_;
        /**
         * <code>int64 term = 1;</code>
         */
        public long getTerm() {
            return term_;
        }

        public static final int INDEX_FIELD_NUMBER = 2;
        private long index_;
        /**
         * <code>int64 index = 2;</code>
         */
        public long getIndex() {
            return index_;
        }

        public static final int DATA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString data_;
        /**
         * <code>bytes data = 3;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (term_ != 0L) {
                output.writeInt64(1, term_);
            }
            if (index_ != 0L) {
                output.writeInt64(2, index_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(3, data_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (term_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, term_);
            }
            if (index_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, index_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, data_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof rpc.LogOuter.LogEntry)) {
                return super.equals(obj);
            }
            rpc.LogOuter.LogEntry other = (rpc.LogOuter.LogEntry) obj;

            boolean result = true;
            result = result && (getTerm()
                    == other.getTerm());
            result = result && (getIndex()
                    == other.getIndex());
            result = result && getData()
                    .equals(other.getData());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TERM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTerm());
            hash = (37 * hash) + INDEX_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getIndex());
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static rpc.LogOuter.LogEntry parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static rpc.LogOuter.LogEntry parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static rpc.LogOuter.LogEntry parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static rpc.LogOuter.LogEntry parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static rpc.LogOuter.LogEntry parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static rpc.LogOuter.LogEntry parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(rpc.LogOuter.LogEntry prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code protobuf.LogEntry}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protobuf.LogEntry)
                rpc.LogOuter.LogEntryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return rpc.LogOuter.internal_static_protobuf_LogEntry_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return rpc.LogOuter.internal_static_protobuf_LogEntry_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                rpc.LogOuter.LogEntry.class, rpc.LogOuter.LogEntry.Builder.class);
            }

            // Construct using rpc.LogOuter.LogEntry.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                term_ = 0L;

                index_ = 0L;

                data_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return rpc.LogOuter.internal_static_protobuf_LogEntry_descriptor;
            }

            @java.lang.Override
            public rpc.LogOuter.LogEntry getDefaultInstanceForType() {
                return rpc.LogOuter.LogEntry.getDefaultInstance();
            }

            @java.lang.Override
            public rpc.LogOuter.LogEntry build() {
                rpc.LogOuter.LogEntry result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public rpc.LogOuter.LogEntry buildPartial() {
                rpc.LogOuter.LogEntry result = new rpc.LogOuter.LogEntry(this);
                result.term_ = term_;
                result.index_ = index_;
                result.data_ = data_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof rpc.LogOuter.LogEntry) {
                    return mergeFrom((rpc.LogOuter.LogEntry)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(rpc.LogOuter.LogEntry other) {
                if (other == rpc.LogOuter.LogEntry.getDefaultInstance()) return this;
                if (other.getTerm() != 0L) {
                    setTerm(other.getTerm());
                }
                if (other.getIndex() != 0L) {
                    setIndex(other.getIndex());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                rpc.LogOuter.LogEntry parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (rpc.LogOuter.LogEntry) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long term_ ;
            /**
             * <code>int64 term = 1;</code>
             */
            public long getTerm() {
                return term_;
            }
            /**
             * <code>int64 term = 1;</code>
             */
            public Builder setTerm(long value) {

                term_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int64 term = 1;</code>
             */
            public Builder clearTerm() {

                term_ = 0L;
                onChanged();
                return this;
            }

            private long index_ ;
            /**
             * <code>int64 index = 2;</code>
             */
            public long getIndex() {
                return index_;
            }
            /**
             * <code>int64 index = 2;</code>
             */
            public Builder setIndex(long value) {

                index_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int64 index = 2;</code>
             */
            public Builder clearIndex() {

                index_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes data = 3;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }
            /**
             * <code>bytes data = 3;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes data = 3;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protobuf.LogEntry)
        }

        // @@protoc_insertion_point(class_scope:protobuf.LogEntry)
        private static final rpc.LogOuter.LogEntry DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new rpc.LogOuter.LogEntry();
        }

        public static rpc.LogOuter.LogEntry getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<LogEntry>
                PARSER = new com.google.protobuf.AbstractParser<LogEntry>() {
            @java.lang.Override
            public LogEntry parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LogEntry(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<LogEntry> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LogEntry> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public rpc.LogOuter.LogEntry getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protobuf_LogEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protobuf_LogEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016logOuter.proto\022\010protobuf\"5\n\010LogEntry\022\014" +
                        "\n\004term\030\001 \001(\003\022\r\n\005index\030\002 \001(\003\022\014\n\004data\030\003 \001(" +
                        "\014B\017\n\003rpcB\010LogOuterb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_protobuf_LogEntry_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protobuf_LogEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protobuf_LogEntry_descriptor,
                new java.lang.String[] { "Term", "Index", "Data", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
