// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package rpc;

public final class RaftOutter {
  private RaftOutter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntryMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.EntryMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 term = 1;</code>
     */
    long getTerm();

    /**
     * <code>.protobuf.EntryType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.protobuf.EntryType type = 2;</code>
     */
    rpc.EnumOutter.EntryType getType();

    /**
     * <code>string peers = 3;</code>
     */
    java.lang.String getPeers();
    /**
     * <code>string peers = 3;</code>
     */
    com.google.protobuf.ByteString
        getPeersBytes();

    /**
     * <code>int64 data_len = 4;</code>
     */
    long getDataLen();

    /**
     * <code>string old_peers = 5;</code>
     */
    java.lang.String getOldPeers();
    /**
     * <code>string old_peers = 5;</code>
     */
    com.google.protobuf.ByteString
        getOldPeersBytes();

    /**
     * <code>int64 checksum = 6;</code>
     */
    long getChecksum();

    /**
     * <code>string learners = 7;</code>
     */
    java.lang.String getLearners();
    /**
     * <code>string learners = 7;</code>
     */
    com.google.protobuf.ByteString
        getLearnersBytes();

    /**
     * <code>string old_learners = 8;</code>
     */
    java.lang.String getOldLearners();
    /**
     * <code>string old_learners = 8;</code>
     */
    com.google.protobuf.ByteString
        getOldLearnersBytes();
  }
  /**
   * Protobuf type {@code protobuf.EntryMeta}
   */
  public  static final class EntryMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.EntryMeta)
      EntryMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntryMeta.newBuilder() to construct.
    private EntryMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntryMeta() {
      term_ = 0L;
      type_ = 0;
      peers_ = "";
      dataLen_ = 0L;
      oldPeers_ = "";
      checksum_ = 0L;
      learners_ = "";
      oldLearners_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntryMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              peers_ = s;
              break;
            }
            case 32: {

              dataLen_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              oldPeers_ = s;
              break;
            }
            case 48: {

              checksum_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              learners_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              oldLearners_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.RaftOutter.internal_static_protobuf_EntryMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.RaftOutter.internal_static_protobuf_EntryMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpc.RaftOutter.EntryMeta.class, rpc.RaftOutter.EntryMeta.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>int64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.protobuf.EntryType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protobuf.EntryType type = 2;</code>
     */
    public rpc.EnumOutter.EntryType getType() {
      @SuppressWarnings("deprecation")
      rpc.EnumOutter.EntryType result = rpc.EnumOutter.EntryType.valueOf(type_);
      return result == null ? rpc.EnumOutter.EntryType.UNRECOGNIZED : result;
    }

    public static final int PEERS_FIELD_NUMBER = 3;
    private volatile java.lang.Object peers_;
    /**
     * <code>string peers = 3;</code>
     */
    public java.lang.String getPeers() {
      java.lang.Object ref = peers_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peers_ = s;
        return s;
      }
    }
    /**
     * <code>string peers = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPeersBytes() {
      java.lang.Object ref = peers_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_LEN_FIELD_NUMBER = 4;
    private long dataLen_;
    /**
     * <code>int64 data_len = 4;</code>
     */
    public long getDataLen() {
      return dataLen_;
    }

    public static final int OLD_PEERS_FIELD_NUMBER = 5;
    private volatile java.lang.Object oldPeers_;
    /**
     * <code>string old_peers = 5;</code>
     */
    public java.lang.String getOldPeers() {
      java.lang.Object ref = oldPeers_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldPeers_ = s;
        return s;
      }
    }
    /**
     * <code>string old_peers = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOldPeersBytes() {
      java.lang.Object ref = oldPeers_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldPeers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKSUM_FIELD_NUMBER = 6;
    private long checksum_;
    /**
     * <code>int64 checksum = 6;</code>
     */
    public long getChecksum() {
      return checksum_;
    }

    public static final int LEARNERS_FIELD_NUMBER = 7;
    private volatile java.lang.Object learners_;
    /**
     * <code>string learners = 7;</code>
     */
    public java.lang.String getLearners() {
      java.lang.Object ref = learners_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        learners_ = s;
        return s;
      }
    }
    /**
     * <code>string learners = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLearnersBytes() {
      java.lang.Object ref = learners_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        learners_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OLD_LEARNERS_FIELD_NUMBER = 8;
    private volatile java.lang.Object oldLearners_;
    /**
     * <code>string old_learners = 8;</code>
     */
    public java.lang.String getOldLearners() {
      java.lang.Object ref = oldLearners_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldLearners_ = s;
        return s;
      }
    }
    /**
     * <code>string old_learners = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOldLearnersBytes() {
      java.lang.Object ref = oldLearners_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldLearners_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeInt64(1, term_);
      }
      if (type_ != rpc.EnumOutter.EntryType.ENTRY_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getPeersBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, peers_);
      }
      if (dataLen_ != 0L) {
        output.writeInt64(4, dataLen_);
      }
      if (!getOldPeersBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, oldPeers_);
      }
      if (checksum_ != 0L) {
        output.writeInt64(6, checksum_);
      }
      if (!getLearnersBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, learners_);
      }
      if (!getOldLearnersBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, oldLearners_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, term_);
      }
      if (type_ != rpc.EnumOutter.EntryType.ENTRY_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getPeersBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, peers_);
      }
      if (dataLen_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, dataLen_);
      }
      if (!getOldPeersBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, oldPeers_);
      }
      if (checksum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, checksum_);
      }
      if (!getLearnersBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, learners_);
      }
      if (!getOldLearnersBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, oldLearners_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rpc.RaftOutter.EntryMeta)) {
        return super.equals(obj);
      }
      rpc.RaftOutter.EntryMeta other = (rpc.RaftOutter.EntryMeta) obj;

      boolean result = true;
      result = result && (getTerm()
          == other.getTerm());
      result = result && type_ == other.type_;
      result = result && getPeers()
          .equals(other.getPeers());
      result = result && (getDataLen()
          == other.getDataLen());
      result = result && getOldPeers()
          .equals(other.getOldPeers());
      result = result && (getChecksum()
          == other.getChecksum());
      result = result && getLearners()
          .equals(other.getLearners());
      result = result && getOldLearners()
          .equals(other.getOldLearners());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PEERS_FIELD_NUMBER;
      hash = (53 * hash) + getPeers().hashCode();
      hash = (37 * hash) + DATA_LEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDataLen());
      hash = (37 * hash) + OLD_PEERS_FIELD_NUMBER;
      hash = (53 * hash) + getOldPeers().hashCode();
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChecksum());
      hash = (37 * hash) + LEARNERS_FIELD_NUMBER;
      hash = (53 * hash) + getLearners().hashCode();
      hash = (37 * hash) + OLD_LEARNERS_FIELD_NUMBER;
      hash = (53 * hash) + getOldLearners().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rpc.RaftOutter.EntryMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RaftOutter.EntryMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rpc.RaftOutter.EntryMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rpc.RaftOutter.EntryMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rpc.RaftOutter.EntryMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.EntryMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.EntryMeta)
        rpc.RaftOutter.EntryMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.RaftOutter.internal_static_protobuf_EntryMeta_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.RaftOutter.internal_static_protobuf_EntryMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpc.RaftOutter.EntryMeta.class, rpc.RaftOutter.EntryMeta.Builder.class);
      }

      // Construct using rpc.RaftOutter.EntryMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        type_ = 0;

        peers_ = "";

        dataLen_ = 0L;

        oldPeers_ = "";

        checksum_ = 0L;

        learners_ = "";

        oldLearners_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.RaftOutter.internal_static_protobuf_EntryMeta_descriptor;
      }

      @java.lang.Override
      public rpc.RaftOutter.EntryMeta getDefaultInstanceForType() {
        return rpc.RaftOutter.EntryMeta.getDefaultInstance();
      }

      @java.lang.Override
      public rpc.RaftOutter.EntryMeta build() {
        rpc.RaftOutter.EntryMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rpc.RaftOutter.EntryMeta buildPartial() {
        rpc.RaftOutter.EntryMeta result = new rpc.RaftOutter.EntryMeta(this);
        result.term_ = term_;
        result.type_ = type_;
        result.peers_ = peers_;
        result.dataLen_ = dataLen_;
        result.oldPeers_ = oldPeers_;
        result.checksum_ = checksum_;
        result.learners_ = learners_;
        result.oldLearners_ = oldLearners_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.RaftOutter.EntryMeta) {
          return mergeFrom((rpc.RaftOutter.EntryMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpc.RaftOutter.EntryMeta other) {
        if (other == rpc.RaftOutter.EntryMeta.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getPeers().isEmpty()) {
          peers_ = other.peers_;
          onChanged();
        }
        if (other.getDataLen() != 0L) {
          setDataLen(other.getDataLen());
        }
        if (!other.getOldPeers().isEmpty()) {
          oldPeers_ = other.oldPeers_;
          onChanged();
        }
        if (other.getChecksum() != 0L) {
          setChecksum(other.getChecksum());
        }
        if (!other.getLearners().isEmpty()) {
          learners_ = other.learners_;
          onChanged();
        }
        if (!other.getOldLearners().isEmpty()) {
          oldLearners_ = other.oldLearners_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpc.RaftOutter.EntryMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpc.RaftOutter.EntryMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 1;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.protobuf.EntryType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protobuf.EntryType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.EntryType type = 2;</code>
       */
      public rpc.EnumOutter.EntryType getType() {
        @SuppressWarnings("deprecation")
        rpc.EnumOutter.EntryType result = rpc.EnumOutter.EntryType.valueOf(type_);
        return result == null ? rpc.EnumOutter.EntryType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.EntryType type = 2;</code>
       */
      public Builder setType(rpc.EnumOutter.EntryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.EntryType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object peers_ = "";
      /**
       * <code>string peers = 3;</code>
       */
      public java.lang.String getPeers() {
        java.lang.Object ref = peers_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peers_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peers = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPeersBytes() {
        java.lang.Object ref = peers_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peers_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peers = 3;</code>
       */
      public Builder setPeers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string peers = 3;</code>
       */
      public Builder clearPeers() {
        
        peers_ = getDefaultInstance().getPeers();
        onChanged();
        return this;
      }
      /**
       * <code>string peers = 3;</code>
       */
      public Builder setPeersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        peers_ = value;
        onChanged();
        return this;
      }

      private long dataLen_ ;
      /**
       * <code>int64 data_len = 4;</code>
       */
      public long getDataLen() {
        return dataLen_;
      }
      /**
       * <code>int64 data_len = 4;</code>
       */
      public Builder setDataLen(long value) {
        
        dataLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 data_len = 4;</code>
       */
      public Builder clearDataLen() {
        
        dataLen_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object oldPeers_ = "";
      /**
       * <code>string old_peers = 5;</code>
       */
      public java.lang.String getOldPeers() {
        java.lang.Object ref = oldPeers_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oldPeers_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string old_peers = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOldPeersBytes() {
        java.lang.Object ref = oldPeers_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldPeers_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string old_peers = 5;</code>
       */
      public Builder setOldPeers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oldPeers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string old_peers = 5;</code>
       */
      public Builder clearOldPeers() {
        
        oldPeers_ = getDefaultInstance().getOldPeers();
        onChanged();
        return this;
      }
      /**
       * <code>string old_peers = 5;</code>
       */
      public Builder setOldPeersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oldPeers_ = value;
        onChanged();
        return this;
      }

      private long checksum_ ;
      /**
       * <code>int64 checksum = 6;</code>
       */
      public long getChecksum() {
        return checksum_;
      }
      /**
       * <code>int64 checksum = 6;</code>
       */
      public Builder setChecksum(long value) {
        
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 checksum = 6;</code>
       */
      public Builder clearChecksum() {
        
        checksum_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object learners_ = "";
      /**
       * <code>string learners = 7;</code>
       */
      public java.lang.String getLearners() {
        java.lang.Object ref = learners_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          learners_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string learners = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLearnersBytes() {
        java.lang.Object ref = learners_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          learners_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string learners = 7;</code>
       */
      public Builder setLearners(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        learners_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string learners = 7;</code>
       */
      public Builder clearLearners() {
        
        learners_ = getDefaultInstance().getLearners();
        onChanged();
        return this;
      }
      /**
       * <code>string learners = 7;</code>
       */
      public Builder setLearnersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        learners_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object oldLearners_ = "";
      /**
       * <code>string old_learners = 8;</code>
       */
      public java.lang.String getOldLearners() {
        java.lang.Object ref = oldLearners_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oldLearners_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string old_learners = 8;</code>
       */
      public com.google.protobuf.ByteString
          getOldLearnersBytes() {
        java.lang.Object ref = oldLearners_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldLearners_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string old_learners = 8;</code>
       */
      public Builder setOldLearners(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oldLearners_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string old_learners = 8;</code>
       */
      public Builder clearOldLearners() {
        
        oldLearners_ = getDefaultInstance().getOldLearners();
        onChanged();
        return this;
      }
      /**
       * <code>string old_learners = 8;</code>
       */
      public Builder setOldLearnersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oldLearners_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.EntryMeta)
    }

    // @@protoc_insertion_point(class_scope:protobuf.EntryMeta)
    private static final rpc.RaftOutter.EntryMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rpc.RaftOutter.EntryMeta();
    }

    public static rpc.RaftOutter.EntryMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntryMeta>
        PARSER = new com.google.protobuf.AbstractParser<EntryMeta>() {
      @java.lang.Override
      public EntryMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntryMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntryMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntryMeta> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rpc.RaftOutter.EntryMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_EntryMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_EntryMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nraft.proto\022\010protobuf\032\nenum.proto\"\252\001\n\tE" +
      "ntryMeta\022\014\n\004term\030\001 \001(\003\022!\n\004type\030\002 \001(\0162\023.p" +
      "rotobuf.EntryType\022\r\n\005peers\030\003 \001(\t\022\020\n\010data" +
      "_len\030\004 \001(\003\022\021\n\told_peers\030\005 \001(\t\022\020\n\010checksu" +
      "m\030\006 \001(\003\022\020\n\010learners\030\007 \001(\t\022\024\n\014old_learner" +
      "s\030\010 \001(\tB\021\n\003rpcB\nRaftOutterb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rpc.EnumOutter.getDescriptor(),
        }, assigner);
    internal_static_protobuf_EntryMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_EntryMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_EntryMeta_descriptor,
        new java.lang.String[] { "Term", "Type", "Peers", "DataLen", "OldPeers", "Checksum", "Learners", "OldLearners", });
    rpc.EnumOutter.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
